version: 2

project_name: secretly

monorepo:
  tag_prefix: cli/
  dir: cmd/cli

builds:
  - id: cli
    main: ./cmd/cli
    binary: secretly-cli
    goos:
      - linux
      - darwin
      - windows

release:
  github:
    owner: jack-kitto
    name: secretly
  draft: true
  name_template: "CLI-v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
