version: 1

project_name: secretly

builds:
  - id: cli
    main: ./cmd/cli
    binary: secretly-cli
    goos:
      - linux
      - darwin
      - windows
  - id: api
    main: ./cmd/api
    binary: secretly-api
    goos:
      - linux
      - darwin
      - windows

release:
  github:
    owner: jack-kitto
    name: secretly
  draft: true
  replace_existing_draft: true
  name_template: "{{.ProjectName}}-v{{.Version}}"
  replace_existing_artifacts: true
  mode: append
  make_latest: true
  include_meta: true
  header: |
    ## Secretly Release {{.Tag}} ({{ .Date }})

    Welcome to this new release of Secretly!
  footer: |
    ## Thanks for using Secretly!

    For more information, please visit our [documentation](https://github.com/jack-kitto/secretly).

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

