name: Release

on:
  push:
    tags:
      - 'cli/v*'
      - 'api/v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: |
        if [[ ${{ github.ref }} == refs/tags/cli/* ]]; then
          make build-cli
        elif [[ ${{ github.ref }} == refs/tags/api/* ]]; then
          make build-api
        fi
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
